model: !!python/object:xgboost.sklearn.XGBClassifier
  base_score: null
  booster: null
  callbacks: null
  colsample_bylevel: null
  colsample_bynode: null
  colsample_bytree: null
  early_stopping_rounds: null
  enable_categorical: false
  eval_metric: logloss
  feature_types: null
  gamma: null
  gpu_id: null
  grow_policy: null
  importance_type: null
  interaction_constraints: null
  learning_rate: 0.3
  max_bin: null
  max_cat_threshold: null
  max_cat_to_onehot: null
  max_delta_step: null
  max_depth: 4
  max_leaves: null
  min_child_weight: 1
  missing: .nan
  monotone_constraints: null
  n_estimators: 50
  n_jobs: null
  num_parallel_tree: null
  objective: binary:logistic
  predictor: null
  random_state: null
  reg_alpha: null
  reg_lambda: null
  sampling_method: null
  scale_pos_weight: null
  subsample: 1.0
  tree_method: null
  use_label_encoder: false
  validate_parameters: null
  verbosity: null
model__eval_metric: logloss
model__learning_rate: 0.3
model__max_depth: 4
model__min_child_weight: 1
model__n_estimators: 50
model__subsample: 1.0
model__use_label_encoder: false